# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1023, 711)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:0.494318 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 0, 1021, 681))
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.CN = QtWidgets.QWidget()
        self.CN.setObjectName("CN")
        self.kernel = QtWidgets.QLabel(self.CN)
        self.kernel.setGeometry(QtCore.QRect(310, 10, 401, 61))
        self.kernel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.kernel.setStyleSheet("background-color: rgba(255, 255, 255, 30);\n"
"font: 22pt \"Times New Roman\";\n"
"border: 1px solid rgba(255, 255, 255, 40);\n"
"border-radius: 7px")
        self.kernel.setAlignment(QtCore.Qt.AlignCenter)
        self.kernel.setObjectName("kernel")
        self.tableView = QtWidgets.QTableView(self.CN)
        self.tableView.setGeometry(QtCore.QRect(20, 130, 991, 421))
        self.tableView.setObjectName("tableView")
        self.add_1 = QtWidgets.QPushButton(self.CN)
        self.add_1.setGeometry(QtCore.QRect(60, 90, 91, 21))
        self.add_1.setStyleSheet("QPushButton {\n"
"   border: 1px solid gray;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"")
        self.add_1.setObjectName("add_1")
        self.delete_1 = QtWidgets.QPushButton(self.CN)
        self.delete_1.setGeometry(QtCore.QRect(150, 90, 91, 21))
        self.delete_1.setStyleSheet("QPushButton {\n"
"   border: 1px solid gray;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}")
        self.delete_1.setObjectName("delete_1")
        self.save_1 = QtWidgets.QPushButton(self.CN)
        self.save_1.setGeometry(QtCore.QRect(800, 560, 91, 21))
        self.save_1.setStyleSheet("QPushButton {\n"
"   border: 1px solid gray;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}")
        self.save_1.setObjectName("save_1")
        self.save_3 = QtWidgets.QPushButton(self.CN)
        self.save_3.setGeometry(QtCore.QRect(710, 560, 91, 21))
        self.save_3.setStyleSheet("QPushButton {\n"
"   border: 1px solid gray;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}")
        self.save_3.setObjectName("save_3")
        self.opora_left = QtWidgets.QCheckBox(self.CN)
        self.opora_left.setGeometry(QtCore.QRect(690, 90, 111, 20))
        self.opora_left.setObjectName("opora_left")
        self.opora_right = QtWidgets.QCheckBox(self.CN)
        self.opora_right.setGeometry(QtCore.QRect(800, 90, 121, 20))
        self.opora_right.setObjectName("opora_right")
        self.open_1 = QtWidgets.QPushButton(self.CN)
        self.open_1.setGeometry(QtCore.QRect(890, 560, 91, 21))
        self.open_1.setStyleSheet("QPushButton {\n"
"   border: 1px solid gray;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"")
        self.open_1.setObjectName("open_1")
        self.tabWidget.addTab(self.CN, "")
        self.Draw = QtWidgets.QWidget()
        self.Draw.setObjectName("Draw")
        self.kernel_5 = QtWidgets.QLabel(self.Draw)
        self.kernel_5.setGeometry(QtCore.QRect(310, 0, 401, 61))
        self.kernel_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.kernel_5.setStyleSheet("background-color: rgba(255, 255, 255, 30);\n"
"font: 22pt \"Times New Roman\";\n"
"border: 1px solid rgba(255, 255, 255, 40);\n"
"border-radius: 7px")
        self.kernel_5.setAlignment(QtCore.Qt.AlignCenter)
        self.kernel_5.setObjectName("kernel_5")
        self.draw_button = QtWidgets.QPushButton(self.Draw)
        self.draw_button.setGeometry(QtCore.QRect(10, 10, 161, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        self.draw_button.setFont(font)
        self.draw_button.setStyleSheet("QPushButton {\n"
"    background-color: qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));\n"
"   border: 1px solid gray;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"")
        self.draw_button.setObjectName("draw_button")
        self.graphicsView = QtWidgets.QGraphicsView(self.Draw)
        self.graphicsView.setGeometry(QtCore.QRect(10, 80, 1001, 551))
        self.graphicsView.setObjectName("graphicsView")
        self.zoom_1 = QtWidgets.QPushButton(self.Draw)
        self.zoom_1.setGeometry(QtCore.QRect(740, 20, 91, 21))
        self.zoom_1.setStyleSheet("QPushButton {\n"
"   border: 1px solid gray;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"")
        self.zoom_1.setObjectName("zoom_1")
        self.zoom_2 = QtWidgets.QPushButton(self.Draw)
        self.zoom_2.setGeometry(QtCore.QRect(850, 20, 91, 21))
        self.zoom_2.setStyleSheet("QPushButton {\n"
"   border: 1px solid gray;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"")
        self.zoom_2.setObjectName("zoom_2")
        self.processor = QtWidgets.QPushButton(self.Draw)
        self.processor.setGeometry(QtCore.QRect(180, 10, 161, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        self.processor.setFont(font)
        self.processor.setStyleSheet("background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(180, 121, 240, 255), stop:0.497326 rgba(213, 145, 230, 255), stop:1 rgba(240, 172, 181, 255));\n"
"")
        self.processor.setObjectName("processor")
        self.tabWidget.addTab(self.Draw, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.tab_2)
        self.graphicsView_2.setGeometry(QtCore.QRect(10, 80, 1001, 551))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.kernel_6 = QtWidgets.QLabel(self.tab_2)
        self.kernel_6.setGeometry(QtCore.QRect(280, 0, 531, 61))
        self.kernel_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.kernel_6.setStyleSheet("background-color: rgba(255, 255, 255, 30);\n"
"font: 22pt \"Times New Roman\";\n"
"border: 1px solid rgba(255, 255, 255, 40);\n"
"border-radius: 7px")
        self.kernel_6.setAlignment(QtCore.Qt.AlignCenter)
        self.kernel_6.setObjectName("kernel_6")
        self.draw_button_2 = QtWidgets.QPushButton(self.tab_2)
        self.draw_button_2.setGeometry(QtCore.QRect(10, 10, 161, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        self.draw_button_2.setFont(font)
        self.draw_button_2.setStyleSheet("QPushButton {\n"
"    background-color: qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));\n"
"   border: 1px solid gray;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"")
        self.draw_button_2.setObjectName("draw_button_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.graphicsView_3 = QtWidgets.QGraphicsView(self.tab_3)
        self.graphicsView_3.setGeometry(QtCore.QRect(10, 80, 1001, 551))
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.kernel_7 = QtWidgets.QLabel(self.tab_3)
        self.kernel_7.setGeometry(QtCore.QRect(280, 0, 531, 61))
        self.kernel_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.kernel_7.setStyleSheet("background-color: rgba(255, 255, 255, 30);\n"
"font: 22pt \"Times New Roman\";\n"
"border: 1px solid rgba(255, 255, 255, 40);\n"
"border-radius: 7px")
        self.kernel_7.setAlignment(QtCore.Qt.AlignCenter)
        self.kernel_7.setObjectName("kernel_7")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.kernel_8 = QtWidgets.QLabel(self.tab_4)
        self.kernel_8.setGeometry(QtCore.QRect(280, 0, 531, 61))
        self.kernel_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.kernel_8.setStyleSheet("background-color: rgba(255, 255, 255, 30);\n"
"font: 22pt \"Times New Roman\";\n"
"border: 1px solid rgba(255, 255, 255, 40);\n"
"border-radius: 7px")
        self.kernel_8.setAlignment(QtCore.Qt.AlignCenter)
        self.kernel_8.setObjectName("kernel_8")
        self.graphicsView_4 = QtWidgets.QGraphicsView(self.tab_4)
        self.graphicsView_4.setGeometry(QtCore.QRect(10, 80, 1001, 551))
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableView_2 = QtWidgets.QTableView(self.tab)
        self.tableView_2.setGeometry(QtCore.QRect(20, 130, 991, 421))
        self.tableView_2.setObjectName("tableView_2")
        self.kernel_2 = QtWidgets.QLabel(self.tab)
        self.kernel_2.setGeometry(QtCore.QRect(310, 10, 401, 61))
        self.kernel_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.kernel_2.setStyleSheet("background-color: rgba(255, 255, 255, 30);\n"
"font: 22pt \"Times New Roman\";\n"
"border: 1px solid rgba(255, 255, 255, 40);\n"
"border-radius: 7px")
        self.kernel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.kernel_2.setObjectName("kernel_2")
        self.tabWidget.addTab(self.tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1023, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setTearOffEnabled(False)
        self.menu.setSeparatorsCollapsible(False)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setCheckable(False)
        self.action_2.setChecked(False)
        self.action_2.setEnabled(True)
        self.action_2.setStatusTip("")
        self.action_2.setWhatsThis("")
        self.action_2.setVisible(True)
        self.action_2.setMenuRole(QtWidgets.QAction.NoRole)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setText("Сохранить")
        self.action_3.setToolTip("Сохранить")
        self.action_3.setObjectName("action_3")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setObjectName("action_5")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.menu.addSeparator()
        self.menu.addAction(self.action_5)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mikael\'s SAPR"))
        self.kernel.setText(_translate("MainWindow", "Создание стержней"))
        self.add_1.setText(_translate("MainWindow", "Добавить"))
        self.delete_1.setText(_translate("MainWindow", "Удалить"))
        self.save_1.setText(_translate("MainWindow", "Сохранить"))
        self.save_3.setText(_translate("MainWindow", "Проверить"))
        self.opora_left.setText(_translate("MainWindow", "Опора слева"))
        self.opora_right.setText(_translate("MainWindow", "Опора справа"))
        self.open_1.setText(_translate("MainWindow", "Открыть"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.CN), _translate("MainWindow", "Параметры стержней"))
        self.kernel_5.setText(_translate("MainWindow", "Отрисовка"))
        self.draw_button.setText(_translate("MainWindow", "Отрисовка"))
        self.zoom_1.setText(_translate("MainWindow", "Увеличить"))
        self.zoom_2.setText(_translate("MainWindow", "Уменьшить"))
        self.processor.setText(_translate("MainWindow", "Расчеты"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Draw), _translate("MainWindow", "Отрисовка"))
        self.kernel_6.setText(_translate("MainWindow", "Продольная сила"))
        self.draw_button_2.setText(_translate("MainWindow", "Отрисовка"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Эпюра Nx"))
        self.kernel_7.setText(_translate("MainWindow", "Перемещение"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Эпюра Ux"))
        self.kernel_8.setText(_translate("MainWindow", "Нормальное напряжение"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Эпюра σx"))
        self.kernel_2.setText(_translate("MainWindow", "Результаты расчетов"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Таблица результатов расчета"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.action_2.setText(_translate("MainWindow", "Открыть"))
        self.action_2.setIconText(_translate("MainWindow", "Открыть"))
        self.action_2.setToolTip(_translate("MainWindow", "Открыть"))
        self.action_3.setIconText(_translate("MainWindow", "Сохранить"))
        self.action_5.setText(_translate("MainWindow", "Выход"))
        self.action.setText(_translate("MainWindow", "пар"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
